/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StockStatus = IDL.Variant({
  'outOfStock' : IDL.Null,
  'available' : IDL.Null,
});
export const CreateProductRequest = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : StockStatus,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const ProductId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'stock' : StockStatus,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'name' : IDL.Text,
  'productId' : ProductId,
  'price' : IDL.Float64,
});
export const CreateOrderRequest = IDL.Record({
  'customerName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'packed' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'orderId' : OrderId,
  'address' : IDL.Text,
  'customerId' : IDL.Principal,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Float64,
});
export const ShopInfo = IDL.Record({
  'latitude' : IDL.Opt(IDL.Float64),
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Opt(IDL.Text),
  'longitude' : IDL.Opt(IDL.Float64),
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const SortBy = IDL.Variant({
  'newest' : IDL.Null,
  'priceDesc' : IDL.Null,
  'priceAsc' : IDL.Null,
});
export const UpdateProductRequest = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : StockStatus,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([CreateProductRequest], [Product], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([CreateOrderRequest], [Order], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getShopInfo' : IDL.Func([], [IDL.Opt(ShopInfo)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listProducts' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(SortBy)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'seedProducts' : IDL.Func([], [IDL.Nat], []),
  'setShopInfo' : IDL.Func([ShopInfo], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  'updateProduct' : IDL.Func([UpdateProductRequest], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StockStatus = IDL.Variant({
    'outOfStock' : IDL.Null,
    'available' : IDL.Null,
  });
  const CreateProductRequest = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : StockStatus,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ProductId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'stock' : StockStatus,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'name' : IDL.Text,
    'productId' : ProductId,
    'price' : IDL.Float64,
  });
  const CreateOrderRequest = IDL.Record({
    'customerName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'packed' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'orderId' : OrderId,
    'address' : IDL.Text,
    'customerId' : IDL.Principal,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Float64,
  });
  const ShopInfo = IDL.Record({
    'latitude' : IDL.Opt(IDL.Float64),
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Opt(IDL.Text),
    'longitude' : IDL.Opt(IDL.Float64),
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const SortBy = IDL.Variant({
    'newest' : IDL.Null,
    'priceDesc' : IDL.Null,
    'priceAsc' : IDL.Null,
  });
  const UpdateProductRequest = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : StockStatus,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([CreateProductRequest], [Product], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([CreateOrderRequest], [Order], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getShopInfo' : IDL.Func([], [IDL.Opt(ShopInfo)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listProducts' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(SortBy)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'seedProducts' : IDL.Func([], [IDL.Nat], []),
    'setShopInfo' : IDL.Func([ShopInfo], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
    'updateProduct' : IDL.Func([UpdateProductRequest], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };