/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateOrderRequest {
  'customerName' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface CreateProductRequest {
  'name' : string,
  'description' : string,
  'stock' : StockStatus,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface Order {
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'email' : string,
  'orderId' : OrderId,
  'address' : string,
  'customerId' : Principal,
  'phone' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : number,
}
export type OrderId = bigint;
export interface OrderItem {
  'qty' : bigint,
  'name' : string,
  'productId' : ProductId,
  'price' : number,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'packed' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'stock' : StockStatus,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export type ProductId = bigint;
export interface ShopInfo {
  'latitude' : [] | [number],
  'city' : string,
  'name' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : [] | [string],
  'longitude' : [] | [number],
  'phone' : string,
  'pincode' : string,
}
export type SortBy = { 'newest' : null } |
  { 'priceDesc' : null } |
  { 'priceAsc' : null };
export type StockStatus = { 'outOfStock' : null } |
  { 'available' : null };
export type Timestamp = bigint;
export interface UpdateProductRequest {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'stock' : StockStatus,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[CreateProductRequest], Product>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[CreateOrderRequest], Order>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getShopInfo' : ActorMethod<[], [] | [ShopInfo]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllOrders' : ActorMethod<[], Array<Order>>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<
    [[] | [string], [] | [string], [] | [SortBy]],
    Array<Product>
  >,
  'seedProducts' : ActorMethod<[], bigint>,
  'setShopInfo' : ActorMethod<[ShopInfo], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'updateProduct' : ActorMethod<[UpdateProductRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];