/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: ProductId;
    name: string;
    createdAt: Timestamp;
    description: string;
    stock: StockStatus;
    imageUrl: string;
    category: string;
    price: number;
}
export type Timestamp = bigint;
export interface OrderItem {
    qty: bigint;
    name: string;
    productId: ProductId;
    price: number;
}
export interface Order {
    customerName: string;
    status: OrderStatus;
    createdAt: Timestamp;
    email: string;
    orderId: OrderId;
    address: string;
    customerId: Principal;
    phone: string;
    items: Array<OrderItem>;
    totalPrice: number;
}
export interface CreateProductRequest {
    name: string;
    description: string;
    stock: StockStatus;
    imageUrl: string;
    category: string;
    price: number;
}
export type ProductId = bigint;
export interface ShopInfo {
    latitude?: number;
    city: string;
    name: string;
    state: string;
    addressLine1: string;
    addressLine2?: string;
    longitude?: number;
    phone: string;
    pincode: string;
}
export interface CreateOrderRequest {
    customerName: string;
    email: string;
    address: string;
    phone: string;
    items: Array<OrderItem>;
}
export type OrderId = bigint;
export interface UpdateProductRequest {
    id: ProductId;
    name: string;
    description: string;
    stock: StockStatus;
    imageUrl: string;
    category: string;
    price: number;
}
export enum OrderStatus {
    shipped = "shipped",
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed",
    packed = "packed"
}
export enum SortBy {
    newest = "newest",
    priceDesc = "priceDesc",
    priceAsc = "priceAsc"
}
export enum StockStatus {
    outOfStock = "outOfStock",
    available = "available"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addProduct(req: CreateProductRequest): Promise<Product>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrder(req: CreateOrderRequest): Promise<Order>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getProduct(id: ProductId): Promise<Product | null>;
    getShopInfo(): Promise<ShopInfo | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllOrders(): Promise<Array<Order>>;
    listMyOrders(): Promise<Array<Order>>;
    listProducts(category: string | null, search: string | null, sortBy: SortBy | null): Promise<Array<Product>>;
    seedProducts(): Promise<bigint>;
    setShopInfo(info: ShopInfo): Promise<void>;
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<boolean>;
    updateProduct(req: UpdateProductRequest): Promise<boolean>;
}
import type { CreateProductRequest as _CreateProductRequest, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, Product as _Product, ProductId as _ProductId, ShopInfo as _ShopInfo, SortBy as _SortBy, StockStatus as _StockStatus, Timestamp as _Timestamp, UpdateProductRequest as _UpdateProductRequest, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addProduct(arg0: CreateProductRequest): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_CreateProductRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_CreateProductRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrder(arg0: CreateOrderRequest): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0);
                return from_candid_Order_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0);
            return from_candid_Order_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShopInfo(): Promise<ShopInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopInfo();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopInfo();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllOrders();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllOrders();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyOrders();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyOrders();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(arg0: string | null, arg1: string | null, arg2: SortBy | null): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedProducts(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.seedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedProducts();
            return result;
        }
    }
    async setShopInfo(arg0: ShopInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setShopInfo(to_candid_ShopInfo_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setShopInfo(to_candid_ShopInfo_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: UpdateProductRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(to_candid_UpdateProductRequest_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(to_candid_UpdateProductRequest_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_OrderStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ShopInfo_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShopInfo): ShopInfo {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StockStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockStatus): StockStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShopInfo]): ShopInfo | null {
    return value.length === 0 ? null : from_candid_ShopInfo_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: _OrderStatus;
    createdAt: _Timestamp;
    email: string;
    orderId: _OrderId;
    address: string;
    customerId: Principal;
    phone: string;
    items: Array<_OrderItem>;
    totalPrice: number;
}): {
    customerName: string;
    status: OrderStatus;
    createdAt: Timestamp;
    email: string;
    orderId: OrderId;
    address: string;
    customerId: Principal;
    phone: string;
    items: Array<OrderItem>;
    totalPrice: number;
} {
    return {
        customerName: value.customerName,
        status: from_candid_OrderStatus_n13(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        email: value.email,
        orderId: value.orderId,
        address: value.address,
        customerId: value.customerId,
        phone: value.phone,
        items: value.items,
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude: [] | [number];
    city: string;
    name: string;
    state: string;
    addressLine1: string;
    addressLine2: [] | [string];
    longitude: [] | [number];
    phone: string;
    pincode: string;
}): {
    latitude?: number;
    city: string;
    name: string;
    state: string;
    addressLine1: string;
    addressLine2?: string;
    longitude?: number;
    phone: string;
    pincode: string;
} {
    return {
        latitude: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.latitude)),
        city: value.city,
        name: value.name,
        state: value.state,
        addressLine1: value.addressLine1,
        addressLine2: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.addressLine2)),
        longitude: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.longitude)),
        phone: value.phone,
        pincode: value.pincode
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    name: string;
    createdAt: _Timestamp;
    description: string;
    stock: _StockStatus;
    imageUrl: string;
    category: string;
    price: number;
}): {
    id: ProductId;
    name: string;
    createdAt: Timestamp;
    description: string;
    stock: StockStatus;
    imageUrl: string;
    category: string;
    price: number;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        stock: from_candid_StockStatus_n7(_uploadFile, _downloadFile, value.stock),
        imageUrl: value.imageUrl,
        category: value.category,
        price: value.price
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} | {
    packed: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : "packed" in value ? OrderStatus.packed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outOfStock: null;
} | {
    available: null;
}): StockStatus {
    return "outOfStock" in value ? StockStatus.outOfStock : "available" in value ? StockStatus.available : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n5(_uploadFile, _downloadFile, x));
}
function to_candid_CreateProductRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProductRequest): _CreateProductRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_ShopInfo_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShopInfo): _ShopInfo {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_SortBy_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): _SortBy {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_StockStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockStatus): _StockStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProductRequest_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProductRequest): _UpdateProductRequest {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy | null): [] | [_SortBy] {
    return value === null ? candid_none() : candid_some(to_candid_SortBy_n26(_uploadFile, _downloadFile, value));
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    stock: StockStatus;
    imageUrl: string;
    category: string;
    price: number;
}): {
    name: string;
    description: string;
    stock: _StockStatus;
    imageUrl: string;
    category: string;
    price: number;
} {
    return {
        name: value.name,
        description: value.description,
        stock: to_candid_StockStatus_n3(_uploadFile, _downloadFile, value.stock),
        imageUrl: value.imageUrl,
        category: value.category,
        price: value.price
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    latitude?: number;
    city: string;
    name: string;
    state: string;
    addressLine1: string;
    addressLine2?: string;
    longitude?: number;
    phone: string;
    pincode: string;
}): {
    latitude: [] | [number];
    city: string;
    name: string;
    state: string;
    addressLine1: string;
    addressLine2: [] | [string];
    longitude: [] | [number];
    phone: string;
    pincode: string;
} {
    return {
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        city: value.city,
        name: value.name,
        state: value.state,
        addressLine1: value.addressLine1,
        addressLine2: value.addressLine2 ? candid_some(value.addressLine2) : candid_none(),
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        phone: value.phone,
        pincode: value.pincode
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductId;
    name: string;
    description: string;
    stock: StockStatus;
    imageUrl: string;
    category: string;
    price: number;
}): {
    id: _ProductId;
    name: string;
    description: string;
    stock: _StockStatus;
    imageUrl: string;
    category: string;
    price: number;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        stock: to_candid_StockStatus_n3(_uploadFile, _downloadFile, value.stock),
        imageUrl: value.imageUrl,
        category: value.category,
        price: value.price
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): {
    newest: null;
} | {
    priceDesc: null;
} | {
    priceAsc: null;
} {
    return value == SortBy.newest ? {
        newest: null
    } : value == SortBy.priceDesc ? {
        priceDesc: null
    } : value == SortBy.priceAsc ? {
        priceAsc: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} | {
    packed: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value == OrderStatus.packed ? {
        packed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockStatus): {
    outOfStock: null;
} | {
    available: null;
} {
    return value == StockStatus.outOfStock ? {
        outOfStock: null
    } : value == StockStatus.available ? {
        available: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
